---
title: "Research"
toc: true 
link-external-newwindow: true
---


## Working Papers

**Child Health and Parental Responses to an Unconditional Cash Transfer at Birth**, with John Lynch, Aurélie Meunier, Rhiannon Pilkington, and <a href="http://www.stefanie-schurer.com">Stefanie Schurer</a>.\
(*Revise and Resubmit* at the **Review of Economics and Statistics**).\
<details>
<summary>Abstract</summary>
We estimate the impact on child health of the unanticipated introduction of the Australian Baby Bonus, a \$3,000 one-off unconditional cash transfer at birth. With population-level administrative data from South Australia and a regression discontinuity design, we find that eligible infants experienced fewer hospital presentations in the first year of life for preventable, acute, and severe problems. In auxiliary analyses using nationally-representative data, we find that the windfall cash allowed parents to increase expenditures on food and groceries, decreased financial stress and hardship, and improved physical and mental health. We calculate that 34\% of the pay-out were recouped within the first year through lower health care costs.
</details>
<a href="https://adegendre.github.io/papers/deGendre_Lynch_Meunier_Pilkington_Schurer_Oct2023.pdf">Working Paper (October 2023)</a> | <a href="https://adegendre.github.io/papers/deGendre_Lynch_Meunier_Pilkington_Schurer_2021_IZA_dp14693.pdf">IZA Discussion Paper (Sep 2021)</a>.\
<a href="https://adegendre.github.io/papers/de_Gendre_NBER_SI_2022.pdf">Slides NBER Summer Institute 2022 (July 2022)</a>.\


**Same-Sex Teacher Effects in Education**, with <a href="https://janfeld.weebly.com">Jan Feld</a>, <a href="https://sites.google.com/view/nsalamanca/home">Nicolás Salamanca</a> and <a href="http://ulfzoelitz.com">Ulf Zölitz</a>.\
<details>
<summary>Abstract</summary>
The idea that students benefit from same-sex teachers has motivated many policies around the world aimed at reducing gender inequalities. However, we do not know the size or generalizability such same-sex teacher effects. We fill this gap by conducting a meta-analysis and our own study using data from 90 countries. Our meta-analysis summarizes the literature and highlights that studies are often underpowered and difficult to compare because they use different methods. Our multi-country study overcomes these shortcomings by providing many high-powered and comparable estimates. Those estimates are ideal for learning about the generalizability of an effect. Our results reveal an interesting pattern. In secondary education, same-sex teacher effects are positive for most countries and outcomes. In primary education, effects are more mixed. For example, we find negative same-sex teacher effects on test scores for about half the countries. Our paper showcases how we can use multi-country studies to learn about the generalizability of an effect.
</details>
<a href="https://adegendre.github.io/papers/deGendre_Feld_Salamanca_Zoelitz_2024.pdf">University of Zurich Working Paper No. 438 (June 2023, Updated May 2024)</a> | <a href="https://www.role-model-effects.com">Website with interactive results</a>.\

**Detecting Local Non-Compliance with Random Treatment Assignment in Quasi-Experiments, with an Application to Ability Peer Effects**, with <a href="https://sites.google.com/view/nsalamanca/home">Nicolás Salamanca</a>.\
<details>
<summary>Abstract</summary>
We develop a method to detect local non-compliance with a random treatment to recover valid quasi-experiments from existing data. Our approach combines simulation-based methods and latent class modelling in an intuitive way, can detect and characterize non-compliant risk sets, and is computationally undemanding. To illustrate its usefulness, we use it to estimate ability peer effects in Taiwan, where we have unusually rich data and a national mandate to randomly assign students to classrooms within schools, but with partial non-compliance. After recovering a valid quasi-experiment, we first estimate ability peer effects in line with other studies. We then document precisely estimated null effects on 18 potential mechanisms, many of which have been hypothesized but never tested. Our application shows how to use our method to expand the causal evidence base using existing datasets.
</details>
<a href="de_Gendre_Salamanca_FishingAlgo_2024.pdf">Latest Version (September 2024)</a>.\
<a href="https://adegendre.github.io/papers/deGendre_Salamanca_2020_IZA_dp13938.pdf">Older Version ("On the Mechanisms of Ability Peer Effects", Dec 2020)</a>.\
Media: <a href="https://theconversation.com/being-in-a-class-with-high-achievers-improves-students-test-scores-we-tried-to-find-out-why-171400">The Conversation (Nov 2021)</a> | ABC Radio Sydney Afternoons (15 Nov 2021).\


**Integrating Minorities in the Classroom: The Role of Students, Parents and Teachers**, with <a href="https://sites.google.com/site/kkarbownik/home?authuser=0">Krzysztof (Chris) Karbownik</a>, <a href="https://sites.google.com/view/nsalamanca/home">Nicolás Salamanca</a> and <a href="https://sites.google.com/site/yvesbzenou">Yves Zenou</a>.\
<details>
<summary>Abstract</summary>
We develop a multi-agent model of the education production function where investments of students, parents, and teachers are linked to the presence of minorities in the classroom. We then test the key implications of this model using rich survey data and a mandate to randomly assign students to classrooms. Consistent with our model, we show that exposure to minority peers decreases student effort, parental investments, and teacher engagement and it results in lower student test scores. Observables correlated with minority status explain less than a third of the reduced-form test score effect while over a third can be descriptively attributed to endogenous responses of the agents.
</details>
<a href="https://adegendre.github.io/papers/CEPR DP 19041.pdf">CEPR Discussion Paper (April 2024)</a>.\
Media: <a href="https://cepr.org/voxeu/columns/how-students-parents-and-teachers-affect-integration-minorities-classroom">VoxEU Column</a>.\    
Other: Best Paper Award at the 2023 Australian Labour Econometrics Workshop.\

   
**Mass Reproducibility and Replicability: A New Hope**, with <a href="https://sites.google.com/site/abelbrodeur/">Abel Brodeur</a>, <a href="https://sites.google.com/view/derekmikola/home">Derek Mikiola</a> and many others.\
<details>
<summary>Abstract</summary>
This study pushes our understanding of research reliability by reproducing and replicating claims from 110 papers in leading economic and political science journals. The analysis involves computational reproducibility checks and robustness assessments. It reveals several patterns. First, we uncover a high rate of fully computationally reproducible results (over 85\%). Second, excluding minor issues like missing packages or broken pathways, we uncover coding errors for about 25\% of studies, with some studies containing multiple errors. Third, we test the robustness of the results to 5,511 re-analyses. We find a robustness reproducibility of about 70\%. Robustness reproducibility rates are relatively higher for re-analyses that introduce new data and lower for re-analyses that change the sample or the definition of the dependent variable. Fourth, 52\% of re-analysis effect size estimates are smaller than the original published estimates and the average statistical significance of a re-analysis is 77\% of the original. Lastly, we rely on six teams of researchers working independently to answer eight additional research questions on the determinants of robustness reproducibility. Most teams find a negative relationship between replicators’ experience and reproducibility, while finding no relationship between reproducibility and the provision of intermediate or even raw data combined with the necessary cleaning codes.\
</details>
<a href="https://adegendre.github.io/papers/I4R-DP107.pdf">I4R Discussion Paper Series (April 2024)</a>.\


**From Subsidies to Loans: The Effects of a National Student Finance Reform on the Choices of Secondary School Students**, with <a href="https://www.jankabatek.com">Jan Kabátek</a>.\
<details>
<summary>Abstract</summary>
We analyse the effects of a national student finance reform in the Netherlands, which replaced universal subsidies for higher education students by low-interest loans. We show that this reform had a large impact on education choices of secondary school students, lowering their enrolments in college-preparing tracks and increasing the share of students specializing in STEM subjects. The reform also affected the living arrangements of new college entrants. Our findings highlight that secondary school students respond to the modes of higher education financing well ahead of their graduation, and that financial aid uncertainty alone can deter many from pursuing higher education.\
</details>
<a href="https://adegendre.github.io/papers/deGendre_Kabatek_2021_IZA_dp14686.pdf">IZA Discussion Paper (Aug 2021)</a>.\
   
   
**Two Decades of Welfare Reforms in Australia: How Did They Affect Single Mothers and Their Children?**, with <a href="http://www.stefanie-schurer.com">Stefanie Schurer</a> and Angela Zhang.\
<details>
<summary>Abstract</summary>
Worldwide, single mothers are profoundly time and income constrained, making them heavily reliant on government transfers. We examine how welfare reforms that introduced mutual obligations affected the economic position of single mothers and the development of their children over the past two decades in Australia. Using nationally representative longitudinal data, we show that disposable incomes of single-mother households were significantly reduced relative to partnered mothers since the 2005 Welfare-to-Work Act came into effect in July 2006, a downward trend that was aggravated by the Global Financial Crisis and the 2013 suspension of grandfathered single parenting payment rules. The reform diminished parenting and family payments for single mothers, who compensated income loss by increasing reliance on disability pension payments, work hours, and child-care expenditures. We then use nationally representative cohort data to estimate the impact of single motherhood on child skill development, following children who entered primary school when their mothers were affected by the Welfare-to-Work reform. We find unadjusted single-motherhood gaps of 0.2 SD in cognitive and 0.3 SD in non-cognitive skills. Non-cognitive skill gaps are only partially explained by differences in observable characteristics, while cognitive skill gaps are fully explained by observable characteristics. Differences in disposable household income between single and partnered mother households explain over 50% of the observed cognitive ability gaps in childhood and 25% in late adolescence. In the presence of positive spillover effects, we propose that welfare payments to vulnerable families may function as a social investment rather than a sunk cost.\
</details>
<a href="https://adegendre.github.io/papers/deGendre_Schurer_Zhang_2021_IZA_dp14752.pdf">IZA Discussion Paper (Sep 2021)</a>.\
   
   
## Publications

<a href="https://doi.org/10.1002/jae.3045">**Re-examining the relationship between patience, risk-taking, and human capital investment across countries**</a> (2024, **Journal of Applied Econometrics**, 1-9.), with <a href="https://janfeld.weebly.com">Jan Feld</a>, <a href="https://sites.google.com/view/nsalamanca/home">Nicolás Salamanca</a>.\
<details>
<summary>Abstract</summary>
Hanushek et al. (2022) show that students in countries in which people are more patient and less risk-taking perform better in the Programme for International Student Assessment (PISA) test. In this paper, we probe the robustness of this study. Our narrow replication shows that the results are mostly robust to alternative model specifications. Our broad replication shows that the main results are robust to measuring student performance with data from The Trends in International Mathematics and Science Study (TIMSS) and The Progress in International Reading Literacy Study (PIRLS) instead of PISA.\
</details>
   
   
## Research in progress

**Class Rank and Sibling Spillover Effects**\
<details>
<summary>Abstract</summary>
This paper studies how students' relative rank affects their younger siblings’ academic performance. Using Dutch administrative data, I exploit within-school, across-cohort variation in student rank. Consistent with previous research, I find that higher-ranked students experience faster human capital accumulation. Yet, these rank effects generate negative spillovers on younger siblings: a one standard deviation increase in rank decreases younger sibling’s test scores by 2 percent of a standard deviation. These spillovers are stronger for same-sex siblings. I show that changes in parental investments and expectations drive part of these spillovers. In particular, I show that migrant parents increase investments in school quality and speaking Dutch at home. My findings highlight that the peer environment creates within-family human capital spillovers.\
</details>
<a href="https://adegendre.github.io/papers/de_Gendre_2021_JMP_Class_Rank_and_Sibling_Spillover_Effects.pdf">Draft JMP version (31 August 2022)</a>.\
   
   
**Affirmative Action during Early Childhood: School Choice, Academic Performance and School Satisfaction**, with <a href="https://sites.google.com/view/shushanikmargaryan">Shushanik Margaryan</a> and <a href="https://sites.google.com/site/josemontalbancastilla/">José Montalban Castilla</a>.\
<details>
<summary>Abstract</summary>
We estimate the impact of income-based priority points on children’s’ outcomes and parental choices from preschool to Grade 6. With administrative records from Madrid, we use two sharp discontinuities in household income per capita which determine income-based priority points within the Boston mechanism. We first show that income-based priority points change parents’ strategy: low-income parents apply to fewer closer schools and schools with lower absenteeism, while higher-income parents apply to more demanded and higher-scoring schools. The priority points increase the likelihood that children are admitted to their preferred school. Yet, we find economically insignificant effects on standardized test scores 6 years later. Lastly, using a matched survey of parents and children, we find small negative effects on parental and child satisfaction with the school, teachers and peers. Our findings indicate that low and higher-income parents respond in sophisticated but different ways to priority rules under the Boston Mechanism.\
</details>
Status: First draft coming soon.\
   

**How do teachers respond to smaller classes? Evidence and implications for student learning**, with <a href="https://www.damonclark.net">Damon Clark, <a href="https://sites.google.com/site/pierredeschampsecon/home">Pierre Deschamps</a>, and <a href="https://sites.google.com/site/josemontalbancastilla/">José Montalban Castilla</a>.\
<details>
<summary>Abstract</summary>
This paper studies how teachers respond to smaller classes and how these responses impact student achievement in the Region of Madrid (Spain), a region of over 1 million school-aged children and 3,000 schools. We exploit the maximum class size rule that generates sharp discontinuities in the relationship between school enrollment and average class size. We estimate the impact of class size reductions on teacher responses and student test scores using regression discontinuity models. We link data covering three key elements at the classroom level: administrative data on student enrollments, administrative data on student test scores and information on teacher responses from teacher survey data covering the universe of teachers and containing rich information on their classroom activities. Our findings shed light on the mechanisms that explain how class size reductions can enhance student learning.\
</details>
Status: Preliminary results.\
   
   
**College Information Provision to Disadvantaged Youth**, with Gloria Chen and <a href="https://siqipan.weebly.com">Siqi Pan</a>.\
Status: RCT in the field.

**The Sources of Researcher Variation in Economics**, with [Nick Huntington-Klein](https://nickchk.com), [Claus Pörtner](http://clausportner.com) and many others. 

<!--
target="_blank" removed because option at top. 
-->