---
title: "Talks"
---

## 2025

Sep-25  CREST Paris invited seminar (scheduled) \
May-25  Paris School of Economics Workshop "Inequality of Opportunity in Education: Evidence and Policies" (scheduled) \
Mar-25  Curtin University invited seminar (scheduled) \
Mar-25  Deakin University invited seminar \

## 2024

Dec-24  Australasia Econometric Society Meeting 2024 \
Nov-24  E61 Institute invited seminar \
Nov-24  UNSW-ESCoE Conference on Economic Measurement 2024 \
Nov-24  Econometrics Workshop at the Department of Economics of the University of Melbourne \
Nov-24  Australian Natural Experiments Workshop 2024, Deakin University \
May-24  European Commission Joint Research Center, Competence Centre on Microeconomic Evaluation invited seminar \

## 2023

Aug-23  University of Technology Sydney \
May-23  University of Melbourne EdFest \
May-23  MetaLab University of Melbourne invited seminar \
May-23  SOLE Annual Meeting (2 talks) \
May-23  University of Melbourne seminar \
Mar-23  University of New South Wales invited seminar \
Jan-23  ADRES Université Paris-Dauphine \
Jan-23  Université Paris-Saclay invited seminar (cancelled) \
Jan-23  CREST Paris invited seminar \

## 2022

Oct-22  "What Works in Education?" STEP UP Conference, UNSW \
Jul-22  NBER Summer Institute 2022 Children \
Jun-22  11th Annual Conference of the American Society of Health Economists (ASHEcon) \
Jan-22	AEA/ASSA Conference	\

## 2021

Dec-21  European Winter Meeting of the Econometric Society 2021 \
Dec-21  University of Potsdam invited seminar \
Nov-21  Irish Postgraduate and Early Career Economics (IPECE) Workshop 2021 \
Sep-21  University of Wollongong invited seminar \
Sep-21	Annual Conference of the European Society of Labour Economics (EALE) \
Aug-21	23rd Australia/New Zealand Labour Econometrics Workshop (LEW) \
Jun-21	HCEO-NES Online Summer School on Socioeconomic Inequality 2021	\
Jun-21	The University of Sydney seminar \
Jun-21	11th International Workshop on Applied Economics of Education (IWAEE)	\
Jun-21	34th Annual Meeting of the European Society of Population Economics	\
Jun-21	Swedish Institute for Social Research (SOFI, Stockholm University)	\

## 2020

Nov-20	The University of Sydney seminar \

## 2019

Sep-19	University of Potsdam 6th PhD Workshop in Empirical Economics	\
Jun-19	10th International Workshop on Applied Economics of Education (IWAEE)	\
May-19	Workshop on The Effectiveness of Children's Education Around the Globe, European University Institute	\
May-19	University College Dublin	invited seminar \
Apr-19	2nd IZA/Briq Behavioral Economics of Education Workshop	\

## 2018

Oct-18	3rd IZA Economics of Education Workshop	\
Oct-18	Applied Micro Workshop of the Department of Economics, The University of Melbourne	\
Aug-18	21st Labor Econometrics Workshop	\
Jun-18	9th International Workshop on Applied Economics of Education (IWAEE)	\
Jun-18	32nd Annual Meeting of the European Society of Population Economics	\
Jun-18	IZA World Labor Conference	\
May-18	IZA 21st Summer School in Labor Economics	\
Apr-18	Applied Micro seminar, Department of Economics, The University of Melbourne	\
Apr-18	RMIT Seminar Series	\

## 2017

Dec-17	Maastricht University, School of Economics seminar	\
Oct-17	Victoria University at Wellington	seminar \
Aug-17	32nd Annual Congress of the European Economic Association and 70th European Meeting of the Econometric Society	\
Jun-17	8th International Workshop on Applied Economics of Education (IWAEE)	\
Jun-17	European Society of Population Economics	\

## 2016

Dec-16	Maastricht University	seminar \
Oct-16	Applied Micro seminar, Melbourne Institute, The University of Melbourne	\
Sep-16	3rd Annual Meeting of the Berlin Interdisciplinary Education Network	\
May-16	Dynamics of Inequalities and their Perceptions, Aix-Marseille Université	\


<!--
Add separation here between body and footer
-->